### PR TITLE
LC PR

### PR DESCRIPTION
**Pull request by johnwcowan**
As we agreed, last call should go for 2 weeks.

### CODE REVIEW

**Comment by lispwright** [comment]
srfi/MANIFEST needs to have the two new NOTES.html files added to it.

It would also make sense with the addition of the srfi/scsh subdirectory for its NOTES.html file to put scsh-build-notes.html and scsh-build-notes.org there, and add them to the MANIFEST file.  Perhaps glob.html in the srfi subdirectory as well to make the top level cleaner?  And add to MANIFEST if so.

README.org and index.html need to have their references to the now withdrawn SRFI 199 removed.

**Comment by arthurgleckler** [comment]
I'm happy with whatever organization you guys implement.  I reviewed this change and merged the pull request, then noticed your comment.  Feel free to amend it.  I'll watch for that.

**Comment by johnwcowan** [comment]
I say go ahead and rearrange the files, remove SRFI 199 reference.

**Comment by lispwright** [comment]
Who "owns" README.org and index.html?

I'll start making a pull request to make the other changes, will wait on the answer to the latter before finishing it.

**Comment by arthurgleckler** [comment]
> Who "owns" README.org and index.html?

I do.  They're generated from "srfi-common/admin/srfi-data.scm".

**Comment by arthurgleckler** [comment]
P.S.: I know that checking in generated files is generally a bad idea.  But since I generate "README.org" for display on Github at the same time as I generate "index.html" for the SRFI web site, I just check them both in.

**Comment by lispwright** [comment]
It's a pretty minor sin.  New PR has been created, tweaking some language, fixing some typos, picking up some missed Chibi Scheme implementation changes (just comments on errno issue), and making the above fixes.

**Pull request merged**
